// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAACcFaVNwp-k4Erx6_A3QUL_hf9cAj5kI',
    appId: '1:1000601178029:web:7b9f89d7994e3334af9b24',
    messagingSenderId: '1000601178029',
    projectId: 'portfolio-nunosilva',
    authDomain: 'portfolio-nunosilva.firebaseapp.com',
    databaseURL: 'https://portfolio-nunosilva-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'portfolio-nunosilva.appspot.com',
    measurementId: 'G-9VFFRD43HS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAX4j6SB2ET54KwZACjHRXpfkohuCBSth0',
    appId: '1:1000601178029:android:4d51baef9efe38dfaf9b24',
    messagingSenderId: '1000601178029',
    projectId: 'portfolio-nunosilva',
    databaseURL: 'https://portfolio-nunosilva-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'portfolio-nunosilva.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMyqFbzr8rvQ-uBR9PoZinGD4ORIIkMaU',
    appId: '1:1000601178029:ios:c1f46210f7c951d9af9b24',
    messagingSenderId: '1000601178029',
    projectId: 'portfolio-nunosilva',
    databaseURL: 'https://portfolio-nunosilva-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'portfolio-nunosilva.appspot.com',
    iosClientId: '1000601178029-sdi5bo55l7hsb71jkv9ih0bhslkrdu8k.apps.googleusercontent.com',
    iosBundleId: 'com.portfolio.app',
  );
}
